trigger: none

resources:
  pipelines:
    - pipeline: dpp
      source: dpp-app-build
      trigger:
        branches:
          include:
            - main
            - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  branchName: $[ replace(resources.pipeline.dpp.sourceBranch, 'refs/heads/', '') ]
  safeNamespace: $[ replace(variables['branchName'], '/', '-') ]

stages:
  - stage: Deploy
    jobs:
      - job: Test
        steps:
          - script: |
              echo $(branchName)
              echo $(safeNamespace)
            displayName: Check variables