{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Throughtput of documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(dpp_documents_uploaded_total[$__rate_interval])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dpp_documents_uploaded_total{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total skipped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dpp_documents_uploaded_total{status=\"skipped\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dpp_documents_uploaded_total{status=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% of uploads completed within X milliseconds.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(dpp_upload_duration_ms_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/health",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}