apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dpp-chart.fullname" . }}-backend
  namespace: monitoring
  labels:
    {{- include "dpp-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "dpp-chart.selectorLabels" (dict "component" "backend" "context" .) | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
