apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dpp-chart.fullname" . }}-svg-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dpp-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.svgStorage.size }}
