trigger: none

schedules:
  - cron: "0 7 * * 1-5"
    displayName: Start AKS
    branches:
      include:
        - main
    always: true

  - cron: "0 19 * * 1-5"
    displayName: Stop AKS
    branches:
      include:
        - main
    always: true

stages:
  - stage: StartAKS
    displayName: Start AKS cluster
    condition: eq(variables['Schedule.DisplayName'], 'Start AKS')
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Start
        steps:
          - task: AzureCLI@2
            displayName: Start AKS cluster
            inputs:
              azureSubscription: azure-ephemeral-dev
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks start \
                  --resource-group dpp-ephemeral-dev \
                  --name dpp-aks

  - stage: StopAKS
    displayName: Stop AKS cluster
    condition: eq(variables['Schedule.DisplayName'], 'Stop AKS')
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Stop
        steps:
          - task: AzureCLI@2
            displayName: Stop AKS cluster
            inputs:
              azureSubscription: azure-ephemeral-dev
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks stop \
                  --resource-group dpp-ephemeral-dev \
                  --name dpp-aks